const colours = {
  pink: [
    { colourName: 'Pink', hex: '#FFC0CB' },
    { colourName: 'LightPink', hex: '#FFB6C1' },
    { colourName: 'HotPink', hex: '#FF69B4' },
    { colourName: 'DeepPink', hex: '#FF1493' },
    { colourName: 'PaleVioletRed', hex: '#DB7093' },
    { colourName: 'MediumVioletRed', hex: '#C71585' },
  ],
  purple: [
    { colourName: 'Lavender', hex: '#E6E6FA' },
    { colourName: 'Thistle', hex: '#D8BFD8' },
    { colourName: 'Plum', hex: '#DDA0DD' },
    { colourName: 'Orchid', hex: '#DA70D6' },
    { colourName: 'Violet', hex: '#EE82EE' },
    { colourName: 'Fuchsia', hex: '#FF00FF' },
    { colourName: 'Magenta', hex: '#FF00FF' },
    { colourName: 'MediumOrchid', hex: '#BA55D3' },
    { colourName: 'DarkOrchid', hex: '#9932CC' },
    { colourName: 'DarkViolet', hex: '#9400D3' },
    { colourName: 'BlueViolet', hex: '#8A2BE2' },
    { colourName: 'DarkMagenta', hex: '#8B008B' },
    { colourName: 'Purple', hex: '#800080' },
    { colourName: 'MediumPurple', hex: '#9370DB' },
    { colourName: 'MediumSlateBlue', hex: '#7B68EE' },
    { colourName: 'SlateBlue', hex: '#6A5ACD' },
    { colourName: 'DarkSlateBlue', hex: '#483D8B' },
    { colourName: 'RebeccaPurple', hex: '#663399' },
    { colourName: 'Indigo', hex: '#4B0082' },
  ],
  red: [
    { colourName: 'LightSalmon', hex: '#FFA07A' },
    { colourName: 'Salmon', hex: '#FA8072' },
    { colourName: 'DarkSalmon', hex: '#E9967A' },
    { colourName: 'LightCoral', hex: '#F08080' },
    { colourName: 'IndianRed', hex: '#CD5C5C' },
    { colourName: 'Crimson', hex: '#DC143C' },
    { colourName: 'Red', hex: '#FF0000' },
    { colourName: 'FireBrick', hex: '#B22222' },
    { colourName: 'DarkRed', hex: '#8B0000' },
  ],
  orange: [
    { colourName: 'Orange', hex: '#FFA500' },
    { colourName: 'DarkOrange', hex: '#FF8C00' },
    { colourName: 'Coral', hex: '#FF7F50' },
    { colourName: 'Tomato', hex: '#FF6347' },
    { colourName: 'OrangeRed', hex: '#FF4500' },
  ],
  yellow: [
    { colourName: 'Gold', hex: '#FFD700' },
    { colourName: 'Yellow', hex: '#FFFF00' },
    { colourName: 'LightYellow', hex: '#FFFFE0' },
    { colourName: 'LemonChiffon', hex: '#FFFACD' },
    { colourName: 'LightGoldenRodYellow', hex: '#FAFAD2' },
    { colourName: 'PapayaWhip', hex: '#FFEFD5' },
    { colourName: 'Moccasin', hex: '#FFE4B5' },
    { colourName: 'PeachPuff', hex: '#FFDAB9' },
    { colourName: 'PaleGoldenRod', hex: '#EEE8AA' },
    { colourName: 'Khaki', hex: '#F0E68C' },
    { colourName: 'DarkKhaki', hex: '#BDB76B' },
  ],
  green: [
    { colourName: 'GreenYellow', hex: '#ADFF2F' },
    { colourName: 'Chartreuse', hex: '#7FFF00' },
    { colourName: 'LawnGreen', hex: '#7CFC00' },
    { colourName: 'Lime', hex: '#00FF00' },
    { colourName: 'LimeGreen', hex: '#32CD32' },
    { colourName: 'PaleGreen', hex: '#98FB98' },
    { colourName: 'LightGreen', hex: '#90EE90' },
    { colourName: 'MediumSpringGreen', hex: '#00FA9A' },
    { colourName: 'SpringGreen', hex: '#00FF7F' },
    { colourName: 'MediumSeaGreen', hex: '#3CB371' },
    { colourName: 'SeaGreen', hex: '#2E8B57' },
    { colourName: 'ForestGreen', hex: '#228B22' },
    { colourName: 'Green', hex: '#008000' },
    { colourName: 'DarkGreen', hex: '#006400' },
    { colourName: 'YellowGreen', hex: '#9ACD32' },
    { colourName: 'OliveDrab', hex: '#6B8E23' },
    { colourName: 'DarkOliveGreen', hex: '#556B2F' },
    { colourName: 'MediumAquaMarine', hex: '#66CDAA' },
    { colourName: 'DarkSeaGreen', hex: '#8FBC8F' },
    { colourName: 'LightSeaGreen', hex: '#20B2AA' },
    { colourName: 'DarkCyan', hex: '#008B8B' },
    { colourName: 'Teal', hex: '#008080' },
  ]
}

export default colours
